#!/usr/bin/env bash

# パッケージゲット
flutter pub get

# arbファイル(文言リソースのJSONファイル)の作成
flutter pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/main.dart

# 生成された雛形のintl_messages.arbをコピーしてintl_ja.arbを作成
# 手動でコピーしてもOK
cat lib/l10n/intl_en.arb | sed -e 's/"@@locale": "messages"/"@@locale": "ja"/g' > lib/l10n/intl_ja.arb

# このタイミングで、必要に応じて、メインの言語以外のarbファイルを用意

# arbファイル群から多言語対応に必要なクラスを生成
# windowsの場合はワイルドカードが効かないので個別に実行すること
flutter packages pub run intl_translation:generate_from_arb --output-dir=lib/l10n --no-use-deferred-loading lib/l10n/l10n.dart lib/l10n/intl_*.arb